export const sidebarItems = [
    { key: "overview", href: "/dashboard" },
    { key: "cropRecommendation", href: "/dashboard/crop-recommendation" },
    { key: "weather", href: "/dashboard/weather" },
    { key: "soilData", href: "/dashboard/soil" },
    { key: "riskAnalysis", href: "/dashboard/risk-analysis" },
    { key: "profitRevenue", href: "/dashboard/economics" },
    { key: "settings", href: "/dashboard/settings" },
];

const common = {
    languageEnglish: "EN",
    languageHindi: "Hindi",
    languageBengali: "Bengali",
};

export const dashboardTranslations = {
    en: {
        ...common,
        overview: "Overview",
        cropRecommendation: "Crop Recommendation",
        weather: "Weather",
        soilData: "Soil Data",
        riskAnalysis: "Risk Analysis",
        profitRevenue: "Profit & Revenue",
        settings: "Settings",
        loadingDashboard: "Loading dashboard...",
        headerCopy:
            "Crop, climate, soil, risk and earning insights for your registered land.",
        farmer: "Farmer",
        logout: "Logout",
        acres: "ac",
        crops: "crops",
        loadingNewApi:
            "Loading crop recommendation and economics data...",
        newApiError: "Recommendation API is not responding yet:",
        temperature: "Temperature",
        thirtyDayTemperature: "30D Avg Temperature",
        humidity: "Humidity",
        rainfall: "Rainfall",
        thirtyDayRainfall: "30D Rainfall",
        thirtyDayAvgRainfall: "30D Avg Daily Rainfall",
        thirtyDayTotalRainfall: "30D Total Rainfall",
        soilPH: "Soil pH",
        nitrogen: "Nitrogen",
        topCropRecommendations: "Top Crop Recommendations",
        overviewApiCopy:
            "Top crops based on soil, humidity, temperature and total rainfall from the last 30 days.",
        loadingOverview: "Loading overview recommendations...",
        rank: "Rank",
        overviewSource: "Overview Inputs",
        overviewSourceCopy:
            "Overview uses 30-day average temperature and 30-day total rainfall for your district.",
        bestCrop: "Best Crop",
        area: "Area",
        harvest: "Harvest",
        days: "days",
        duration: "Duration",
        waterRequirement: "water requirement",
        confidence: "Confidence",
        yield: "Yield",
        revenue: "Revenue",
        profit: "Profit",
        roi: "ROI",
        liveWeatherInputs: "Weather Inputs",
        fiveDayForecast: "5-Day Forecast",
        loadingForecast: "Loading forecast...",
        forecastMissing: "Forecast API key is not configured.",
        phosphorus: "Phosphorus (P)",
        potassium: "Potassium (K)",
        diseaseRiskFromApi: "Disease Risk",
        diseaseRiskCopy:
            "Risk analysis uses disease alerts returned with each crop recommendation.",
        alert: "Alert",
        noAlert: "No alert",
        noDiseaseRisk: "No disease risk returned by the current recommendation.",
        economicsTitle: "Profit, Loss & Revenue Calculator",
        economicsCopy:
            "Values are calculated for your registered land area.",
        crop: "Crop",
        price: "Price",
        cost: "Cost",
        profitLoss: "Profit/Loss",
        district: "District",
        landAreaAcres: "Land Area (acres)",
        settingsCopy:
            "Update your district and land area to refresh weather, crop and economics results.",
        saveSettings: "Save Changes",
        savingSettings: "Saving...",
        settingsSaved: "Settings updated. Refreshing dashboard data...",
        settingsError: "Unable to update settings",
        districtRequired: "District is required",
        landAreaRequired: "Land area must be greater than 0",
        manualSoilTitle: "Improve Recommendation Accuracy",
        manualSoilCopy:
            "These recommendations were generated using estimated soil values. If you have laboratory-tested values, enter them below and regenerate recommendations.",
        currentNitrogen: "Current N",
        currentPhosphorus: "Current P",
        currentPotassium: "Current K",
        currentPH: "Current pH",
        nitrogenInput: "Nitrogen (N)",
        phosphorusInput: "Phosphorus (P)",
        potassiumInput: "Potassium (K)",
        phInput: "pH",
        regenerateRecommendations: "Regenerate Recommendations",
        regeneratingRecommendations: "Regenerating...",
        regenerateLoadingSteps: [
            "Reading your manual soil values...",
            "Refreshing crop suitability with updated NPK and pH...",
            "Recalculating yield, revenue and ROI...",
            "Preparing the updated recommendation list...",
        ],
    },
    hi: {
        ...common,
        overview: "अवलोकन",
        cropRecommendation: "फसल सुझाव",
        weather: "मौसम",
        soilData: "मिट्टी डेटा",
        riskAnalysis: "जोखिम विश्लेषण",
        profitRevenue: "लाभ और आय",
        settings: "सेटिंग्स",
        loadingDashboard: "डैशबोर्ड लोड हो रहा है...",
        headerCopy:
            "आपकी पंजीकृत जमीन के लिए फसल, मौसम, मिट्टी, जोखिम और आय की जानकारी।",
        farmer: "किसान",
        logout: "लॉगआउट",
        acres: "एकड़",
        crops: "फसलें",
        loadingNewApi:
            "फसल सुझाव और आर्थिक डेटा लोड हो रहा है...",
        newApiError: "सुझाव API अभी जवाब नहीं दे रही है:",
        temperature: "तापमान",
        thirtyDayTemperature: "30 दिन का औसत तापमान",
        humidity: "नमी",
        rainfall: "वर्षा",
        thirtyDayRainfall: "30 दिन की वर्षा",
        thirtyDayAvgRainfall: "30 दिन की औसत दैनिक वर्षा",
        thirtyDayTotalRainfall: "30 दिन की कुल वर्षा",
        soilPH: "मिट्टी pH",
        nitrogen: "नाइट्रोजन",
        topCropRecommendations: "शीर्ष फसल सुझाव",
        overviewApiCopy:
            "पिछले 30 दिनों की मिट्टी, नमी, तापमान और कुल वर्षा के आधार पर शीर्ष फसलें।",
        loadingOverview: "अवलोकन सुझाव लोड हो रहे हैं...",
        rank: "रैंक",
        overviewSource: "अवलोकन इनपुट",
        overviewSourceCopy:
            "अवलोकन आपके जिले के 30 दिन के औसत तापमान और 30 दिन की कुल वर्षा का उपयोग करता है।",
        bestCrop: "सर्वश्रेष्ठ फसल",
        area: "क्षेत्रफल",
        harvest: "कटाई",
        days: "दिन",
        duration: "अवधि",
        waterRequirement: "पानी की जरूरत",
        confidence: "विश्वास",
        yield: "उपज",
        revenue: "आय",
        profit: "लाभ",
        roi: "ROI",
        liveWeatherInputs: "मौसम इनपुट",
        fiveDayForecast: "5 दिन का पूर्वानुमान",
        loadingForecast: "पूर्वानुमान लोड हो रहा है...",
        forecastMissing: "Forecast API key configured नहीं है।",
        phosphorus: "फॉस्फोरस (P)",
        potassium: "पोटैशियम (K)",
        diseaseRiskFromApi: "रोग जोखिम",
        diseaseRiskCopy:
            "जोखिम विश्लेषण हर फसल सुझाव के साथ मिले disease alert का उपयोग करता है।",
        alert: "अलर्ट",
        noAlert: "कोई अलर्ट नहीं",
        noDiseaseRisk: "मौजूदा सुझाव में कोई रोग जोखिम नहीं मिला।",
        economicsTitle: "लाभ, हानि और आय कैलकुलेटर",
        economicsCopy:
            "मान आपकी पंजीकृत जमीन के क्षेत्रफल के लिए निकाले गए हैं।",
        crop: "फसल",
        price: "कीमत",
        cost: "लागत",
        profitLoss: "लाभ/हानि",
        district: "जिला",
        landAreaAcres: "जमीन का क्षेत्रफल (एकड़)",
        settingsCopy:
            "मौसम, फसल और आर्थिक परिणामों को अपडेट करने के लिए जिला और जमीन का क्षेत्रफल बदलें।",
        saveSettings: "बदलाव सेव करें",
        savingSettings: "सेव हो रहा है...",
        settingsSaved: "सेटिंग्स अपडेट हो गईं। डैशबोर्ड डेटा रीफ्रेश हो रहा है...",
        settingsError: "सेटिंग्स अपडेट नहीं हो सकीं",
        districtRequired: "जिला जरूरी है",
        landAreaRequired: "जमीन का क्षेत्रफल 0 से अधिक होना चाहिए",
        manualSoilTitle: "सुझाव की सटीकता बढ़ाएं",
        manualSoilCopy:
            "ये सुझाव अनुमानित मिट्टी मानों से बने हैं। अगर आपके पास लैब-जांच वाले मान हैं, तो उन्हें नीचे डालकर सुझाव दोबारा बनाएं।",
        currentNitrogen: "वर्तमान N",
        currentPhosphorus: "वर्तमान P",
        currentPotassium: "वर्तमान K",
        currentPH: "वर्तमान pH",
        nitrogenInput: "नाइट्रोजन (N)",
        phosphorusInput: "फॉस्फोरस (P)",
        potassiumInput: "पोटैशियम (K)",
        phInput: "pH",
        regenerateRecommendations: "सुझाव दोबारा बनाएं",
        regeneratingRecommendations: "दोबारा बनाया जा रहा है...",
        regenerateLoadingSteps: [
            "आपके मैनुअल मिट्टी मान पढ़े जा रहे हैं...",
            "अपडेट किए गए NPK और pH से फसल उपयुक्तता जांची जा रही है...",
            "उपज, आय और ROI दोबारा निकाले जा रहे हैं...",
            "नई सुझाव सूची तैयार हो रही है...",
        ],
    },
    bn: {
        ...common,
        overview: "ওভারভিউ",
        cropRecommendation: "ফসল পরামর্শ",
        weather: "আবহাওয়া",
        soilData: "মাটির তথ্য",
        riskAnalysis: "ঝুঁকি বিশ্লেষণ",
        profitRevenue: "লাভ ও আয়",
        settings: "সেটিংস",
        loadingDashboard: "ড্যাশবোর্ড লোড হচ্ছে...",
        headerCopy:
            "আপনার নিবন্ধিত জমির জন্য ফসল, আবহাওয়া, মাটি, ঝুঁকি ও আয়ের তথ্য।",
        farmer: "কৃষক",
        logout: "লগআউট",
        acres: "একর",
        crops: "ফসল",
        loadingNewApi:
            "ফসল পরামর্শ ও অর্থনৈতিক ডেটা লোড হচ্ছে...",
        newApiError: "পরামর্শ API এখনও সাড়া দিচ্ছে না:",
        temperature: "তাপমাত্রা",
        thirtyDayTemperature: "৩০ দিনের গড় তাপমাত্রা",
        humidity: "আর্দ্রতা",
        rainfall: "বৃষ্টিপাত",
        thirtyDayRainfall: "৩০ দিনের বৃষ্টিপাত",
        thirtyDayAvgRainfall: "৩০ দিনের গড় দৈনিক বৃষ্টিপাত",
        thirtyDayTotalRainfall: "৩০ দিনের মোট বৃষ্টিপাত",
        soilPH: "মাটির pH",
        nitrogen: "নাইট্রোজেন",
        topCropRecommendations: "সেরা ফসল পরামর্শ",
        overviewApiCopy:
            "গত ৩০ দিনের মাটি, আর্দ্রতা, তাপমাত্রা ও মোট বৃষ্টিপাতের ভিত্তিতে সেরা ফসল।",
        loadingOverview: "ওভারভিউ পরামর্শ লোড হচ্ছে...",
        rank: "র‍্যাঙ্ক",
        overviewSource: "ওভারভিউ ইনপুট",
        overviewSourceCopy:
            "ওভারভিউ আপনার জেলার ৩০ দিনের গড় তাপমাত্রা এবং ৩০ দিনের মোট বৃষ্টিপাত ব্যবহার করে।",
        bestCrop: "সেরা ফসল",
        area: "জমির পরিমাণ",
        harvest: "ফসল কাটার সময়",
        days: "দিন",
        duration: "সময়কাল",
        waterRequirement: "পানির প্রয়োজন",
        confidence: "বিশ্বাসযোগ্যতা",
        yield: "উৎপাদন",
        revenue: "আয়",
        profit: "লাভ",
        roi: "ROI",
        liveWeatherInputs: "আবহাওয়া ইনপুট",
        fiveDayForecast: "৫ দিনের পূর্বাভাস",
        loadingForecast: "পূর্বাভাস লোড হচ্ছে...",
        forecastMissing: "Forecast API key configured নয়।",
        phosphorus: "ফসফরাস (P)",
        potassium: "পটাশিয়াম (K)",
        diseaseRiskFromApi: "রোগের ঝুঁকি",
        diseaseRiskCopy:
            "ঝুঁকি বিশ্লেষণ প্রতিটি ফসল পরামর্শের disease alert ব্যবহার করে।",
        alert: "সতর্কতা",
        noAlert: "কোনো সতর্কতা নেই",
        noDiseaseRisk: "বর্তমান পরামর্শে কোনো রোগের ঝুঁকি পাওয়া যায়নি।",
        economicsTitle: "লাভ, ক্ষতি ও আয়ের ক্যালকুলেটর",
        economicsCopy:
            "মানগুলো আপনার নিবন্ধিত জমির পরিমাণ অনুযায়ী হিসাব করা হয়েছে।",
        crop: "ফসল",
        price: "দাম",
        cost: "খরচ",
        profitLoss: "লাভ/ক্ষতি",
        district: "জেলা",
        landAreaAcres: "জমির পরিমাণ (একর)",
        settingsCopy:
            "আবহাওয়া, ফসল ও অর্থনৈতিক ফলাফল রিফ্রেশ করতে জেলা এবং জমির পরিমাণ আপডেট করুন।",
        saveSettings: "পরিবর্তন সেভ করুন",
        savingSettings: "সেভ হচ্ছে...",
        settingsSaved: "সেটিংস আপডেট হয়েছে। ড্যাশবোর্ড ডেটা রিফ্রেশ হচ্ছে...",
        settingsError: "সেটিংস আপডেট করা যায়নি",
        districtRequired: "জেলা প্রয়োজন",
        landAreaRequired: "জমির পরিমাণ ০-এর বেশি হতে হবে",
        manualSoilTitle: "পরামর্শের নির্ভুলতা বাড়ান",
        manualSoilCopy:
            "এই পরামর্শগুলি আনুমানিক মাটির মান দিয়ে তৈরি হয়েছে। আপনার কাছে ল্যাব-পরীক্ষিত মান থাকলে নিচে দিয়ে পরামর্শ আবার তৈরি করুন।",
        currentNitrogen: "বর্তমান N",
        currentPhosphorus: "বর্তমান P",
        currentPotassium: "বর্তমান K",
        currentPH: "বর্তমান pH",
        nitrogenInput: "নাইট্রোজেন (N)",
        phosphorusInput: "ফসফরাস (P)",
        potassiumInput: "পটাশিয়াম (K)",
        phInput: "pH",
        regenerateRecommendations: "পরামর্শ আবার তৈরি করুন",
        regeneratingRecommendations: "আবার তৈরি হচ্ছে...",
        regenerateLoadingSteps: [
            "আপনার ম্যানুয়াল মাটির মান পড়া হচ্ছে...",
            "আপডেট করা NPK এবং pH দিয়ে ফসলের উপযোগিতা দেখা হচ্ছে...",
            "উৎপাদন, আয় এবং ROI আবার হিসাব করা হচ্ছে...",
            "নতুন পরামর্শ তালিকা তৈরি হচ্ছে...",
        ],
    },
};

export const formatInr = (value) =>
    new Intl.NumberFormat("en-IN", {
        style: "currency",
        currency: "INR",
        maximumFractionDigits: 0,
    }).format(Number(value || 0));

export const formatNumber = (value, digits = 1) => {
    const number = Number(value);
    if (!Number.isFinite(number)) return "0";
    return number.toLocaleString("en-IN", {
        maximumFractionDigits: digits,
    });
};

export const cropConfidence = (crop) => {
    const confidence = Number(crop?.confidence_pct ?? crop?.confidence ?? 0);
    return confidence <= 1 ? confidence * 100 : confidence;
};

export const cropTranslations = {
    en: {
        apple: "Apple",
        banana: "Banana",
        blackgram: "Blackgram",
        chickpea: "Chickpea",
        coconut: "Coconut",
        coffee: "Coffee",
        cotton: "Cotton",
        grapes: "Grapes",
        jute: "Jute",
        kidneybeans: "Kidney Beans",
        lentil: "Lentil",
        maize: "Maize",
        mango: "Mango",
        mothbeans: "Moth Beans",
        mungbean: "Mung Bean",
        muskmelon: "Muskmelon",
        orange: "Orange",
        papaya: "Papaya",
        pigeonpeas: "Pigeon Peas",
        pomegranate: "Pomegranate",
        rice: "Rice",
        watermelon: "Watermelon",
    },
    hi: {
        apple: "सेब",
        banana: "केला",
        blackgram: "उड़द",
        chickpea: "चना",
        coconut: "नारियल",
        coffee: "कॉफी",
        cotton: "कपास",
        grapes: "अंगूर",
        jute: "जूट",
        kidneybeans: "राजमा",
        lentil: "मसूर",
        maize: "मक्का",
        mango: "आम",
        mothbeans: "मोठ",
        mungbean: "मूंग",
        muskmelon: "खरबूजा",
        orange: "संतरा",
        papaya: "पपीता",
        pigeonpeas: "अरहर",
        pomegranate: "अनार",
        rice: "धान",
        watermelon: "तरबूज",
    },
    bn: {
        apple: "আপেল",
        banana: "কলা",
        blackgram: "মাষকলাই",
        chickpea: "ছোলা",
        coconut: "নারকেল",
        coffee: "কফি",
        cotton: "তুলা",
        grapes: "আঙুর",
        jute: "পাট",
        kidneybeans: "রাজমা",
        lentil: "মসুর",
        maize: "ভুট্টা",
        mango: "আম",
        mothbeans: "মথ বিন",
        mungbean: "মুগ",
        muskmelon: "খরমুজ",
        orange: "কমলা",
        papaya: "পেঁপে",
        pigeonpeas: "অড়হর",
        pomegranate: "ডালিম",
        rice: "ধান",
        watermelon: "তরমুজ",
    },
};

export const getCropName = (crop, language = "en") => {
    const key = String(crop || "").toLowerCase();
    return cropTranslations[language]?.[key] || cropTranslations.en[key] || crop;
};
